### ISSUE TITLE
Issue with running kubectl commands

### ISSUE THREAD

**Issue by zestrells** [kodermax/kubectl-aws-eks#17]
Hello @kodermax !

I am experiencing issues when using this.
Logs:
```
  WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
```

Issue:
```
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v[1]
```

**Comment by kosta1221** [comment]
Hello, I am experiencing the same problem. It looks like the cause is described here:

https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/386
and here:
https://stackoverflow.com/questions/71318743/kubectl-versions-error-exec-plugin-is-configured-to-use-api-version-client-auth

I inspected my kubeconfig file (that I am passing to this action) and indeed saw that I am using `v1alpha`. I will change it and report if it works.

**Comment by Hacks4Snacks** [comment]
'curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl' in Dockerfile is pulling latest stable kubectl (1.24) that is not compatible with "client.authentication.k8s.io/v1alpha1" - (what I observed with my 1.21 cluster and tested with a previous kubectl version).

**Comment by zestrells** [comment]
@Hacks4Snacks did you solve by changing to v1beta1 to solve this ?

**Comment by ckuroki** [comment]
Same problem here. And it's not solved by changing to v1beta1

**Comment by kosta1221** [comment]
I could not solve as well. Tried both aws eks get-token and aws-iam-authenticator

**Comment by viktorvillalobos** [comment]
Same problem here, still without solution.

**Comment by chevronjenkins** [comment]
Same problem here, i change to v1beta1 but i just had another error

**Comment by rbg** [comment]
we are seeing the same issue ..

**Comment by kosta1221** [comment]
I think that I have figured it out. Thank you @Hacks4Snacks for bringing up the fact that kubectl version 1.24 is the root cause of the problem because it does not support `client.authentication.k8s.io/v1alpha1` (I tested it and confirmed).

This means that unfortunately the easiest way of automatically generating the kubeconfig file used by this action via `aws eks update-kubeconfig` will not work because it always outputs `ExecCredential`s with apiVersion `client.authentication.k8s.io/v1alpha1` (tested with aws-cli 2.6.1).

As previously discussed, we are left with `aws-iam-authenticator` version 0.5.5 and up which outputs `ExecCredential`s with apiVersion `client.authentication.k8s.io/v1beta1`. I tested it and got it working locally.

This action uses `aws-iam-authenticator` version 0.5.3, which outputs `ExecCredential`s with apiVersion `client.authentication.k8s.io/v1alpha1`, and so it means that this github action is currently broken unless I am missing something.

This is why I proposed https://github.com/kodermax/kubectl-aws-eks/pull/19 where the aws-iam-authenticator is updated to 0.5.7 to be able to use this action with new versions of kubectl via `aws-iam-authenticator`.
The alternative of course will be to explicitly install kubectl with a lower version than 1.24

**Comment by Hacks4Snacks** [comment]
@kosta1221 I think moving the aws-iam-authenticator version makes sense. As an alternative (or in addition to), I am proposing #20 which adds a simple check for the existence of an environment variable named "KUBECTL_VERSION". If "KUBECTL_VERSION" exists, delete the installed version of kubectl (latest) and replace it with the defined version.

example usage:
      - name: Example Name
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "v1.22.0"
        with:
          args: rollout restart deployment -n <namespace> <deployment_name>

**Comment by rbg** [comment]
@Hacks4Snacks @kosta1221 both great solutions i think i prefer @Hacks4Snacks ; i did whip this out too https://github.com/evosecurity/kubectl-aws-eks

**Comment by baigzeeshan** [comment]
I have fixed it (for me) by forking the repo and updating the kubectl version to 1.22.6, which is the same as EKS https://github.com/datanextsolutions/kubectl-aws-eks

**Comment by lululombard** [comment]
> I have fixed it (for me) by forking the repo and updating the kubectl version to 1.22.6, which is the same as EKS https://github.com/datanextsolutions/kubectl-aws-eks

That's good news! Did you open a PR so we can all benefit from this update? Thanks!

**Comment by baigzeeshan** [comment]
> > I have fixed it (for me) by forking the repo and updating the kubectl version to 1.22.6, which is the same as EKS https://github.com/datanextsolutions/kubectl-aws-eks
> 
> That's good news! Did you open a PR so we can all benefit from this update? Thanks!

We might need a multi-branch model with different kubectl versions, so one can pick which version to use in their workflow. I will see if I can submit a PR. 

The best temporary fix is to fork the repo and use that in your workflow.

**Comment by dk253** [comment]
Well, the solution moved me a bit further (thanks!).  But now I'm getting:

"The config profile (xxx) could not be found"

Any clues?

**Comment by baigzeeshan** [comment]
> Well, the solution moved me a bit further (thanks!). But now I'm getting:
> 
> "The config profile (xxx) could not be found"
> 
> Any clues?

The current code does not take a AWS_PROFILE name in KUBE_CONFIG_DATA variable. You need to remove the profile from the kube/config file and use the default AWS_PROFILE 

Here's an example, you need to convert it to base64 

`apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: xxx==
      server: https://xxx.xxx.xxxx.eks.amazonaws.com
    name: arn:aws:eks:xxxx:xxxxx:cluster/my-eks-cluster
contexts:
  - context:
      cluster: arn:aws:eks:xxxx:xxxxx:cluster/my-eks-cluster
      user: arn:aws:eks:xxxx:xxxxx:cluster/my-eks-cluster
    name: arn:aws:eks:xxxx:xxxxx:cluster/my-eks-cluster
current-context: arn:aws:eks:xxxx:xxxxx:cluster/my-eks-cluster
kind: Config
preferences: {}
users:
  - name: arn:aws:eks:xxxx:xxxxx:cluster/my-eks-cluster
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        args:
          - --region
          - us-east-1
          - eks
          - get-token
          - --cluster-name
          - my-eks-cluster
        command: aws
`

**Comment by dk253** [comment]
My apologies!  In an effort to resolve this problem before this thread was started, I recreated my config data and the process stuck the profile on the end of the file.  Your help fixed it.  Thanks!!!!

**Comment by normeno** [comment]
> I have fixed it (for me) by forking the repo and updating the kubectl version to 1.22.6, which is the same as EKS https://github.com/datanextsolutions/kubectl-aws-eks

This works for me, thanks @baigzeeshan .

**Comment by mikeallisonJS** [comment]
I see a new version was pushed to address this, but there is no documentation. Anyone know how to set the kubectl version?

**Comment by Hacks4Snacks** [comment]
@mikeallisonJS 

In your GitHub workflow file, you just need to add the KUBECTL_VERSION environment variable.

example usage:
- name: Example Name
uses: kodermax/kubectl-aws-eks@master
env:
KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
**KUBECTL_VERSION: "v1.22.0"**
with:
args: rollout restart deployment -n <namespace_name> <deployment_name>

**Comment by KarthickEka** [comment]
I have to change this in a lot of repositories. Is there an easy way to do this?

**Comment by normeno** [comment]
> 



> @mikeallisonJS
> 
> In your GitHub workflow file, you just need to add the KUBECTL_VERSION environment variable.
> 
> example usage:
> 
> * name: Example Name
>   uses: kodermax/kubectl-aws-eks@master
>   env:
>   KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
>   **KUBECTL_VERSION: "v1.22.0"**
>   with:
>   args: rollout restart deployment -n <namespace_name> <deployment_name>

I'm trying this, but I get an error

![image](https://user-images.githubusercontent.com/6278347/166842033-a86110f9-1ba2-4803-9445-b3adaee45d55.png)

**Comment by Hacks4Snacks** [comment]
@normeno

For the KUBECTL_VERSION variable, did you put:

KUBECTL_VERSION: "v1.21.2" or
KUBECTL_VERSION: "1.21.2"

If you put KUBECTL_VERSION: "1.21.2" it will fail as is script isn't sophisticated enough to add the required "v" for the url version. For now, you, must include the v in front of the kubectl version e.g., "v1.21.2"

**Comment by normeno** [comment]
> @normeno
> 
> For the KUBECTL_VERSION variable, did you put:
> 
> KUBECTL_VERSION: "v1.21.2" or KUBECTL_VERSION: "1.21.2"
> 
> If you put KUBECTL_VERSION: "1.21.2" it will fail as is script isn't sophisticated enough to add the required "v" for the url version. For now, you must include the v in front of the kubectl version e.g., "v1.21.2"

@Hacks4Snacks my bad, you're right. I must use v1.21.2 and not 1.21.2. Now it worked fine, thank you very much

**Comment by kosta1221** [comment]
To whomever stumbles upon this issue and is still confused about what to do:
* If you just want to see all possible options, skip to 'Summary of all possible options'

It really boils down to 2 conditions:

a. `kubectl` has to support the API version to use when decoding the ExecCredentials resource
b. There are 2 API versions (the versions to use when decoding the ExecCredentials resource) which need to match. 
1. The API version returned by the auth plugin
2. The API version which is listed in the kubeconfig.

There are currently 3 versions of `client.authentication.k8s.io`: `client.authentication.k8s.io/v1alpha1`, `client.authentication.k8s.io/v1beta1` and `client.authentication.k8s.io/v1`

- If `kubectl` is of version 1.24 or higher, it does not support `client.authentication.k8s.io/v1alpha1`.
- Auth plugin aws eks get-token uses only `client.authentication.k8s.io/v1alpha1` currently.
- Auth plugin aws-iam-authenticator version <=v0.5.3 uses `client.authentication.k8s.io/v1alpha1`, and version >=v0.5.4 uses `client.authentication.k8s.io/v1beta1`

Based on our conditions, there are 3 variables at play and their combination can either make or break your pipeline. These variables are:
- `kubectl` version
- The auth plugin you are using in your kubeconfig and its version
- The API version which is listed in your kubeconfig.

how kubectl version divides our options:
kubectl version: >=1.24
possible auth plugins: aws-iam-authenticator
kubeconfig possible api versions: v1beta1

kubectl version: <1.24
possible auth plugins: aws-iam-authenticator, aws eks get-token (aws cli)
kubeconfig possible api versions: v1beta1, v1alpha1

Summary of all possible options:

OPTION 1:
kubectl version: >=1.24
auth plugin: aws-iam-authenticator version >=0.5.4
kubeconfig api version: v1beta1

example action usage:
```yaml
- name: Verify Deployment
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: rollout status deployment/my-dep
```

example kubeconfig's users section:
```yaml
users:
- name: arn:aws:eks:$region_code:$account_id:cluster/$cluster_name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "$cluster_name"
```

OPTION 2:
kubectl version: <1.24
auth plugin: aws-iam-authenticator version >=0.5.4
kubeconfig api version: v1beta1

example action usage:
```yaml
- name: Verify Deployment
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          KUBECTL_VERSION: "v1.22.0"
        with:
          args: rollout status deployment/my-dep
```

example kubeconfig's users section:
```yaml
users:
- name: arn:aws:eks:$region_code:$account_id:cluster/$cluster_name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "$cluster_name"
```

OPTION 3:
kubectl version: <1.24
auth plugin: aws-iam-authenticator version <=0.5.3
kubeconfig api version: v1alpha1

example action usage:
```yaml
- name: Verify Deployment
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          KUBECTL_VERSION: "v1.22.0"
          IAM_VERSION: "0.5.3"
        with:
          args: rollout status deployment/my-dep
```

example kubeconfig's users section:
```yaml
users:
- name: arn:aws:eks:$region_code:$account_id:cluster/$cluster_name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "$cluster_name"
```

OPTION 4:
kubectl version: <1.24
auth plugin: aws eks get-token (aws cli)
kubeconfig api version: v1alpha1

example action usage:
```yaml
- name: Verify Deployment
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          KUBECTL_VERSION: "v1.22.0"
        with:
          args: rollout status deployment/my-dep
```

example kubeconfig's users section:
```yaml
users:
- name: arn:aws:eks:$region_code:$account_id:cluster/$cluster_name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - <REGION>
      - eks
      - get-token
      - --cluster-name
      - <CLUSTER-NAME>
      command: aws
```

NOTE: If you are using the  `aws eks update-kubeconfig` command, your kubeconfig's users section will be updated with the aws eks get-token command so you will have to use OPTION 4.

I hope that this helps with the confusion.
