### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by Elycin** [kodermax/kubectl-aws-eks#4]
Hey there,

I've been using this action pretty extensively and it has worked wonders, I created a new repository today for my EKS cluster and made the following rolling deployment change.

```yml
      - name: Rolling Deployment for Backend
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_STAGING }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: {{ REPO }}
          IMAGE_TAG: ${{ github.sha }}
        with:
          args: set image deployment {{ REPO }} {{ REPO }}=${{ steps.login-ecr.outputs.registry }}/{{ REPO }}:${{ github.sha }} --record
```

I received the following error form the pipeline:
```
Run kodermax/kubectl-aws-eks@master
  with:
    args: set image deployment safewords-backend safewords-backend=***.dkr.ecr.eu-west-2.amazonaws.com/safewords:a31f52e5b9da06fc1447f8926c3d9ac2ab9ed25d --record
  env:
    AWS_DEFAULT_REGION: eu-west-2
    AWS_REGION: eu-west-2
    KUBE_CONFIG_DATA: 
    ECR_REGISTRY: ***.dkr.ecr.eu-west-2.amazonaws.com
    ECR_REPOSITORY: [REPO]
    IMAGE_TAG: a31f52e5b9da06fc1447f8926c3d9ac2ab9ed25d
/usr/bin/docker run --name b1cbc5c3a06d339ad242069d90bf6f1cb78e93_ab9e55 --label b1cbc5 --workdir /github/workspace --rm -e AWS_DEFAULT_REGION -e AWS_REGION -e KUBE_CONFIG_DATA -e ECR_REGISTRY -e ECR_REPOSITORY -e IMAGE_TAG -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/_work/_temp/_github_home":"/github/home" -v "/home/runner/_work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/_work/[repo]/[repo]":"/github/workspace" b1cbc5:c3a06d339ad242069d90bf6f1cb78e93 set image deployment [repo] [repo]=***.dkr.ecr.eu-west-2.amazonaws.com/[REPO]:a31f52e5b9da06fc1447f8926c3d9ac2ab9ed25d --record
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

By any chance, is there something I am missing, or a role on IAM?

Thanks in advance,
Ely Haughie
