### ISSUE TITLE
Getting credentials error on deployment to cluster

### ISSUE THREAD

**Issue by OpenDataAlex** [kodermax/kubectl-aws-eks#7]
While running my Github Action, I receive the following:

`Unable to connect to the server: getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1alpha1, plugin returned version client.authentication.k8s.io/v1beta1`

I have been running my kubernetes deployment for over a year just fine and my script has not been modified.  The relevant block from my actions script:
```

- name: deploy to cluster
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.PROJECT_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        with: 
          args: set image -n kube-system deployment/repo-name $ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
```
